---
- name: Install dependencies for Redis. | Package install
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ redis_package_dependencies }}"

- name: Install Redis | Package install
  package:
    name: redis
  register: _redis_repo_install

# Moving to configure-server.yml after config file has been moved
# - name: Start and enable Redis service. | Package install
#   service:
#     name: "{{ redis_service_name }}"
#     state: started
#     enabled: true