---
- name: Install package dependencies for Redis | Package install
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ redis_package_dependencies }}"

- name: Install Redis | Package install
  package:
    name: redis
  register: _redis_repo_install
