---
- include_tasks: preflight.yml

- include_tasks: install-package.yml
  when: not redis_install_from_source

- include_tasks: install-source.yml
  when: redis_install_from_source

- include_tasks: configure.yml
