---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-redis-tls
    image: ghcr.io/miarec/${MOLECULE_DISTRO:-ubuntu2404}-systemd:latest
    command: ${MOLECULE_DOCKER_COMMAND:-"/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
    environment:
      container: docker
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../
verifier:
  name: testinfra
  options:
    s: true
    verbose: true
