---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Define install variables
      set_fact:
        redis_install_from_source: false

    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_facts["os_family"] == "Debian"

  roles:
    - role: ansible-role-redis
      tags:
        - redis
