---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        redis_version: "{{ lookup('env', 'REDIS_VERSION') }}"

    - name: Install prerequisites
      block:
        - name: Update apt cache
          when: ansible_os_family == "Debian"
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false

  roles:
    - role: ansible-role-redis
      tags:
        - redis
