---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        redis_install_from_source: false

    # RHEL 8 and 9, redis package is in appstream repo,
    # https://access.redhat.com/downloads/content/redis/6.2.7-1.module+el8.7.0+15197+cc495aeb/x86_64/fd431d51/package
    # https://access.redhat.com/downloads/content/redis/7.0.12-1.module+el9.3.0+19307+b7a69809/x86_64/fd431d51/package
    # UBI appstream repository does not inclued a redis package
    # Install Centos appstream repository for testing
    - name: Install Addtional Repositories | RHEL8+
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version >= "8"
      block:

      - set_fact:
          _tmp_repos:
            - name: appstream
              url: http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/
              gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official
        when: ansible_distribution_major_version == "8"

      - set_fact:
          _tmp_repos:
            - name: appstream
              url: https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/
              gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official
        when: ansible_distribution_major_version == "9"

      - name: Add appstream Repository | RHEL 8+
        yum_repository:
            name: "{{ item.name }}"
            description: "Centos {{ ansible_distribution_major_version }} - {{ item.name }}"
            baseurl: "{{ item.url }}"
            enabled: true
            gpgkey: "{{ item.gpg }}"
        with_items: "{{ _tmp_repos }}"
        loop_control:
          label: "{{ item.name }}"

    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

  roles:
    - role: ansible-role-redis
      tags:
        - redis
